- hosts: all
  user: root
  tasks:
    - name: output message.
      debug: msg="{{ message }}"

    - name: output fruits
      debug: msg="We want {{ item.value.amount }} {{ item.key }} !" 
      with_dict: "{{ fruits }}"
    - name: install epel package from yum 
      yum: name=epel-release state=latest
      
    - name: install package from yum 
      yum: name={{ item }} state=latest
      with_items:
       - ruby
       - httpd
    - name: create directories
      file: path={{ item.path }} owner={{ item.owner }} group={{ item.group }} mode=0{{ item.mode }} state=directory
      with_items:
        - { "path":"/opt/ansible", "owner":"root", "group":"root", "mode":"755" }
        - { "path":"/opt/vagrant", "owner":"vagrant", "group":"vagrant", "mode":"755" }
    - name: copy files
      copy: src=./files/hoge dest=/opt/ansible/hoge owner=root group=root mode=0755

    - name: copy template files
      template: src=./templates/fuga.j2 dest=/opt/ansible/fuga owner=root group=root mode=0755  

- hosts: node2
  user: root
  tasks:
    - name: install epel package from yum 
      yum: name=epel-release state=latest
   